name: Release build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y mingw-w64 make

      - name: Build
        run: make

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dll-files
          path: build

      - name: Create release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: build/32/xinput1_3.dll
